# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hyperbox.v1 import control_pb2 as hyperbox_dot_v1_dot_control__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hyperbox/v1/control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HyperboxControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSandbox = channel.unary_unary(
                '/hyperbox.v1.HyperboxControl/CreateSandbox',
                request_serializer=hyperbox_dot_v1_dot_control__pb2.CreateSandboxRequest.SerializeToString,
                response_deserializer=hyperbox_dot_v1_dot_control__pb2.CreateSandboxResponse.FromString,
                _registered_method=True)
        self.DestroySandbox = channel.unary_unary(
                '/hyperbox.v1.HyperboxControl/DestroySandbox',
                request_serializer=hyperbox_dot_v1_dot_control__pb2.DestroySandboxRequest.SerializeToString,
                response_deserializer=hyperbox_dot_v1_dot_control__pb2.DestroySandboxResponse.FromString,
                _registered_method=True)
        self.InspectSandbox = channel.unary_unary(
                '/hyperbox.v1.HyperboxControl/InspectSandbox',
                request_serializer=hyperbox_dot_v1_dot_control__pb2.InspectSandboxRequest.SerializeToString,
                response_deserializer=hyperbox_dot_v1_dot_control__pb2.InspectSandboxResponse.FromString,
                _registered_method=True)
        self.Exec = channel.unary_unary(
                '/hyperbox.v1.HyperboxControl/Exec',
                request_serializer=hyperbox_dot_v1_dot_control__pb2.ExecRequest.SerializeToString,
                response_deserializer=hyperbox_dot_v1_dot_control__pb2.ExecResponse.FromString,
                _registered_method=True)
        self.ReadFile = channel.unary_unary(
                '/hyperbox.v1.HyperboxControl/ReadFile',
                request_serializer=hyperbox_dot_v1_dot_control__pb2.ReadFileRequest.SerializeToString,
                response_deserializer=hyperbox_dot_v1_dot_control__pb2.ReadFileResponse.FromString,
                _registered_method=True)
        self.WriteFile = channel.unary_unary(
                '/hyperbox.v1.HyperboxControl/WriteFile',
                request_serializer=hyperbox_dot_v1_dot_control__pb2.WriteFileRequest.SerializeToString,
                response_deserializer=hyperbox_dot_v1_dot_control__pb2.WriteFileResponse.FromString,
                _registered_method=True)
        self.ListTemplates = channel.unary_unary(
                '/hyperbox.v1.HyperboxControl/ListTemplates',
                request_serializer=hyperbox_dot_v1_dot_control__pb2.ListTemplatesRequest.SerializeToString,
                response_deserializer=hyperbox_dot_v1_dot_control__pb2.ListTemplatesResponse.FromString,
                _registered_method=True)
        self.GetMetrics = channel.unary_unary(
                '/hyperbox.v1.HyperboxControl/GetMetrics',
                request_serializer=hyperbox_dot_v1_dot_control__pb2.MetricsRequest.SerializeToString,
                response_deserializer=hyperbox_dot_v1_dot_control__pb2.MetricsResponse.FromString,
                _registered_method=True)
        self.GetServerInfo = channel.unary_unary(
                '/hyperbox.v1.HyperboxControl/GetServerInfo',
                request_serializer=hyperbox_dot_v1_dot_control__pb2.ServerInfoRequest.SerializeToString,
                response_deserializer=hyperbox_dot_v1_dot_control__pb2.ServerInfoResponse.FromString,
                _registered_method=True)
        self.CreateSnapshot = channel.unary_unary(
                '/hyperbox.v1.HyperboxControl/CreateSnapshot',
                request_serializer=hyperbox_dot_v1_dot_control__pb2.CreateSnapshotRequest.SerializeToString,
                response_deserializer=hyperbox_dot_v1_dot_control__pb2.CreateSnapshotResponse.FromString,
                _registered_method=True)
        self.RestoreSnapshot = channel.unary_unary(
                '/hyperbox.v1.HyperboxControl/RestoreSnapshot',
                request_serializer=hyperbox_dot_v1_dot_control__pb2.RestoreSnapshotRequest.SerializeToString,
                response_deserializer=hyperbox_dot_v1_dot_control__pb2.RestoreSnapshotResponse.FromString,
                _registered_method=True)


class HyperboxControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSandbox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroySandbox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InspectSandbox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exec(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTemplates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HyperboxControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSandbox,
                    request_deserializer=hyperbox_dot_v1_dot_control__pb2.CreateSandboxRequest.FromString,
                    response_serializer=hyperbox_dot_v1_dot_control__pb2.CreateSandboxResponse.SerializeToString,
            ),
            'DestroySandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroySandbox,
                    request_deserializer=hyperbox_dot_v1_dot_control__pb2.DestroySandboxRequest.FromString,
                    response_serializer=hyperbox_dot_v1_dot_control__pb2.DestroySandboxResponse.SerializeToString,
            ),
            'InspectSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.InspectSandbox,
                    request_deserializer=hyperbox_dot_v1_dot_control__pb2.InspectSandboxRequest.FromString,
                    response_serializer=hyperbox_dot_v1_dot_control__pb2.InspectSandboxResponse.SerializeToString,
            ),
            'Exec': grpc.unary_unary_rpc_method_handler(
                    servicer.Exec,
                    request_deserializer=hyperbox_dot_v1_dot_control__pb2.ExecRequest.FromString,
                    response_serializer=hyperbox_dot_v1_dot_control__pb2.ExecResponse.SerializeToString,
            ),
            'ReadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=hyperbox_dot_v1_dot_control__pb2.ReadFileRequest.FromString,
                    response_serializer=hyperbox_dot_v1_dot_control__pb2.ReadFileResponse.SerializeToString,
            ),
            'WriteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteFile,
                    request_deserializer=hyperbox_dot_v1_dot_control__pb2.WriteFileRequest.FromString,
                    response_serializer=hyperbox_dot_v1_dot_control__pb2.WriteFileResponse.SerializeToString,
            ),
            'ListTemplates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTemplates,
                    request_deserializer=hyperbox_dot_v1_dot_control__pb2.ListTemplatesRequest.FromString,
                    response_serializer=hyperbox_dot_v1_dot_control__pb2.ListTemplatesResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=hyperbox_dot_v1_dot_control__pb2.MetricsRequest.FromString,
                    response_serializer=hyperbox_dot_v1_dot_control__pb2.MetricsResponse.SerializeToString,
            ),
            'GetServerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerInfo,
                    request_deserializer=hyperbox_dot_v1_dot_control__pb2.ServerInfoRequest.FromString,
                    response_serializer=hyperbox_dot_v1_dot_control__pb2.ServerInfoResponse.SerializeToString,
            ),
            'CreateSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSnapshot,
                    request_deserializer=hyperbox_dot_v1_dot_control__pb2.CreateSnapshotRequest.FromString,
                    response_serializer=hyperbox_dot_v1_dot_control__pb2.CreateSnapshotResponse.SerializeToString,
            ),
            'RestoreSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreSnapshot,
                    request_deserializer=hyperbox_dot_v1_dot_control__pb2.RestoreSnapshotRequest.FromString,
                    response_serializer=hyperbox_dot_v1_dot_control__pb2.RestoreSnapshotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hyperbox.v1.HyperboxControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hyperbox.v1.HyperboxControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HyperboxControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperbox.v1.HyperboxControl/CreateSandbox',
            hyperbox_dot_v1_dot_control__pb2.CreateSandboxRequest.SerializeToString,
            hyperbox_dot_v1_dot_control__pb2.CreateSandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroySandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperbox.v1.HyperboxControl/DestroySandbox',
            hyperbox_dot_v1_dot_control__pb2.DestroySandboxRequest.SerializeToString,
            hyperbox_dot_v1_dot_control__pb2.DestroySandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InspectSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperbox.v1.HyperboxControl/InspectSandbox',
            hyperbox_dot_v1_dot_control__pb2.InspectSandboxRequest.SerializeToString,
            hyperbox_dot_v1_dot_control__pb2.InspectSandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperbox.v1.HyperboxControl/Exec',
            hyperbox_dot_v1_dot_control__pb2.ExecRequest.SerializeToString,
            hyperbox_dot_v1_dot_control__pb2.ExecResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperbox.v1.HyperboxControl/ReadFile',
            hyperbox_dot_v1_dot_control__pb2.ReadFileRequest.SerializeToString,
            hyperbox_dot_v1_dot_control__pb2.ReadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperbox.v1.HyperboxControl/WriteFile',
            hyperbox_dot_v1_dot_control__pb2.WriteFileRequest.SerializeToString,
            hyperbox_dot_v1_dot_control__pb2.WriteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTemplates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperbox.v1.HyperboxControl/ListTemplates',
            hyperbox_dot_v1_dot_control__pb2.ListTemplatesRequest.SerializeToString,
            hyperbox_dot_v1_dot_control__pb2.ListTemplatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperbox.v1.HyperboxControl/GetMetrics',
            hyperbox_dot_v1_dot_control__pb2.MetricsRequest.SerializeToString,
            hyperbox_dot_v1_dot_control__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperbox.v1.HyperboxControl/GetServerInfo',
            hyperbox_dot_v1_dot_control__pb2.ServerInfoRequest.SerializeToString,
            hyperbox_dot_v1_dot_control__pb2.ServerInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperbox.v1.HyperboxControl/CreateSnapshot',
            hyperbox_dot_v1_dot_control__pb2.CreateSnapshotRequest.SerializeToString,
            hyperbox_dot_v1_dot_control__pb2.CreateSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestoreSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperbox.v1.HyperboxControl/RestoreSnapshot',
            hyperbox_dot_v1_dot_control__pb2.RestoreSnapshotRequest.SerializeToString,
            hyperbox_dot_v1_dot_control__pb2.RestoreSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HyperboxAgentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Exec = channel.unary_unary(
                '/hyperbox.v1.HyperboxAgent/Exec',
                request_serializer=hyperbox_dot_v1_dot_control__pb2.ExecRequest.SerializeToString,
                response_deserializer=hyperbox_dot_v1_dot_control__pb2.ExecResponse.FromString,
                _registered_method=True)
        self.ReadFile = channel.unary_unary(
                '/hyperbox.v1.HyperboxAgent/ReadFile',
                request_serializer=hyperbox_dot_v1_dot_control__pb2.ReadFileRequest.SerializeToString,
                response_deserializer=hyperbox_dot_v1_dot_control__pb2.ReadFileResponse.FromString,
                _registered_method=True)
        self.WriteFile = channel.unary_unary(
                '/hyperbox.v1.HyperboxAgent/WriteFile',
                request_serializer=hyperbox_dot_v1_dot_control__pb2.WriteFileRequest.SerializeToString,
                response_deserializer=hyperbox_dot_v1_dot_control__pb2.WriteFileResponse.FromString,
                _registered_method=True)
        self.Shell = channel.stream_stream(
                '/hyperbox.v1.HyperboxAgent/Shell',
                request_serializer=hyperbox_dot_v1_dot_control__pb2.ShellRequest.SerializeToString,
                response_deserializer=hyperbox_dot_v1_dot_control__pb2.ShellEvent.FromString,
                _registered_method=True)


class HyperboxAgentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Exec(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shell(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HyperboxAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Exec': grpc.unary_unary_rpc_method_handler(
                    servicer.Exec,
                    request_deserializer=hyperbox_dot_v1_dot_control__pb2.ExecRequest.FromString,
                    response_serializer=hyperbox_dot_v1_dot_control__pb2.ExecResponse.SerializeToString,
            ),
            'ReadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=hyperbox_dot_v1_dot_control__pb2.ReadFileRequest.FromString,
                    response_serializer=hyperbox_dot_v1_dot_control__pb2.ReadFileResponse.SerializeToString,
            ),
            'WriteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteFile,
                    request_deserializer=hyperbox_dot_v1_dot_control__pb2.WriteFileRequest.FromString,
                    response_serializer=hyperbox_dot_v1_dot_control__pb2.WriteFileResponse.SerializeToString,
            ),
            'Shell': grpc.stream_stream_rpc_method_handler(
                    servicer.Shell,
                    request_deserializer=hyperbox_dot_v1_dot_control__pb2.ShellRequest.FromString,
                    response_serializer=hyperbox_dot_v1_dot_control__pb2.ShellEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hyperbox.v1.HyperboxAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hyperbox.v1.HyperboxAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HyperboxAgent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Exec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperbox.v1.HyperboxAgent/Exec',
            hyperbox_dot_v1_dot_control__pb2.ExecRequest.SerializeToString,
            hyperbox_dot_v1_dot_control__pb2.ExecResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperbox.v1.HyperboxAgent/ReadFile',
            hyperbox_dot_v1_dot_control__pb2.ReadFileRequest.SerializeToString,
            hyperbox_dot_v1_dot_control__pb2.ReadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperbox.v1.HyperboxAgent/WriteFile',
            hyperbox_dot_v1_dot_control__pb2.WriteFileRequest.SerializeToString,
            hyperbox_dot_v1_dot_control__pb2.WriteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shell(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/hyperbox.v1.HyperboxAgent/Shell',
            hyperbox_dot_v1_dot_control__pb2.ShellRequest.SerializeToString,
            hyperbox_dot_v1_dot_control__pb2.ShellEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
