[package]
name = "hyperbox-network"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
hickory-proto = "0.24"
regex.workspace = true
serde.workspace = true
tokio.workspace = true
hyperbox-core = { path = "../hyperbox-core" }
